### ISSUE TITLE
What is the purpose of the duke3d.grp option? (and question about items not included)

### ISSUE THREAD

**Issue by sofakng** [NightFright2k19/worldtour_raze#4]
First off, thanks for the fantastic script!

Question though... what's the purpose of the option asking to copy and convert the duke3d.grp from World Tour?

Also, it's noted that a few things aren't included in the script (maps/music/duketalk for ep1-4, ep1-4 skyboxes, commentaries, etc).  Is this because they aren't supported in Raze?

**Comment by NightFright2k19** [comment]
World Tour is changing quite a few tiles. Converting to Atomic brings those back. In general it is not totally necessary, which is why it is an option.

The script is going for a minimal approach, i.e. it is stripping any resources which are not needed to run the new episode. Also, some features such as dev commentaries are not supported in other ports, which is why they aren't included in the first place.
